### PR TITLE
Allow trailing slashes

### PR DESCRIPTION
**Pull request by jayvdb**

### CODE REVIEW

**Comment by jayvdb** [comment]
@retr0h , wrt "(No longer maintained)" , would you care to allow other people to help maintaining this.  @sks444 , @virresh and/or myself from @coala would be able to help.

I had this packaged for openSUSE. https://software.opensuse.org/package/python3-git-url-parse

**Comment by retr0h** [comment]
@jayvdb  I knew you would come back :)  I removed issues because I couldn't maintain this code, and was unsuccessful in getting your interest in fixing issues when /cc'ing you guys.

**Comment by jayvdb** [comment]
I'm very sorry I missed your messages. I tend to work on priority queues where I am a maintainer. Anyway, offer stands. Happy to take a greater role. Ideal would be moving the repo under coala, so it uses our queues. But that is optional.

**Comment by retr0h** [comment]
> I'm very sorry I missed your messages. I tend to work on priority queues where I am a maintainer. Anyway, offer stands. Happy to take a greater role. Ideal would be moving the repo under coala, so it uses our queues. But that is optional.

I'm happy to transfer it, let me know.

**Comment by jayvdb** [comment]
I've sent you an invite to join @coala , which I think you need to be able to do the transfer.  After the transfer you can leave again if you want.

**Pull request merged**
