### PR TITLE
VersionInfo('git-url-parse')

### PR DESCRIPTION
**Pull request by hamr**
Grab version info from this package, not molecule.

### CODE REVIEW

**Comment by retr0h** [comment]
Thanks @hamr mistake on my part!  Thanks for catching that.

**Comment by hamr** [comment]
Sure, thanks for all these nice python packages!

**Comment by hamr** [comment]
Hey @retr0h, would you mind making a release of this and making it available on pypi?  Then I'll be able to `pip install python-gilt`.

**Comment by retr0h** [comment]
Hey @hamr sorry about that.  Totally forgot.  Here ya [go](https://pypi.python.org/pypi/git-url-parse).

**Comment by hamr** [comment]
Thanks again!

**Pull request merged**
